Fixed docker-compose file
The current docker-compose file gives an error 
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'dst-server'
```

It's obviously missing the version, and I don't know about restart policy, but i've changed this parameter according to one of my docker-compose files as well. Now it's working properly.